# Generated by Django 4.2.30 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_summary_es_course_summary_fr_course_title_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='uploadvideo',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='course',
            name='summary_sw',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_sw',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='summary_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_sw',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='summary_sw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadvideo',
            name='title_sw',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
