# Generated by Django 4.2.30 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_choice_choice_es_choice_choice_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_es',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_fr',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_sw',
            field=models.CharField(help_text='Enter the choice text that you want displayed', max_length=1000, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='question',
            name='content_sw',
            field=models.CharField(help_text='Enter the question text that you want displayed', max_length=1000, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_sw',
            field=models.TextField(blank=True, help_text='Explanation to be shown after the question has been answered.', max_length=2000, null=True, verbose_name='Explanation'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description_sw',
            field=models.TextField(blank=True, help_text='A detailed description of the quiz', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='title_sw',
            field=models.CharField(max_length=60, null=True, verbose_name='Title'),
        ),
    ]
