# Generated by Django 4.2.30 on 2026-06-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Form 6', 'Form 6')], max_length=25, null=True),
        ),
    ]
